var businessTypeColorsArray =["#D15242",
"#B075CA",
"#C6872E",
"#5D8FC2",
"#E44624",
"#9D2A70",
"#DE405B",
"#CF58E6",
"#D9E439",
"#4B78DC",
"#C77D6A",
"#E7A72D"]
var colorsCategories = {
    "government":1,
    "retail":2,
    "entertainment":3,
    "health":4,
    "finance":5,
    "office":6,
    "food":7,
    "placeOfWorship":0,
    "culture":9,
    "other":10
}
var businessTypeColors = {"department_store":"retail",
"establishment":"other",
"point_of_interest":"other",
"embassy":"government",
"beauty_salon":"entertainment",
"police":"government",
"courthouse":"government",
"cemetery":"government",
"pharmacy":"retail",
"local_government_office": "government",
"shopping_mall":"retail",
"hardware_store":"retail",
"city_hall": "government",
"finance": "finance",
"food":"food",
"shoe_store":"retail",
"bank":"finance",
"bowling_alley":"entertainment",
"place_of_worship":"placeOfWorship",
"bar":"entertainment",
"car_dealer":"retail",
"movie_theater":"entertainment",
"grocery_or_supermarket":"retail",
"fire_station":"government",
"church":"placeOfWorship",
"convenience_store":"retail",
"lawyer": "office",
"post_office":"government",
"health":"health",
"meal_takeaway":"food",
"movie_rental":"entertainment",
"gas_station":"retail",
"funeral_home":"retail",
"restaurant":"food",
"home_goods_store":"retail",
"atm":"retail",
"mosque":"placeOfWorship",
"veterinary_care":"health",
"locksmith":"retail",
"museum":"culture",
"night_club":"entertainment",
"electrician": "retail",
"lodging": "retail",
"florist": "retail",
"liquor_store":"retail",
"hospital":"health",
"car_rental":"retail",
"stadium":"government",
"store":"retail",
"hair_care":"retail",
"meal_delivery":"food",
"dentist":"health",
"library":"culture",
"book_store":"retail",
"painter":"retail",
"roofing_contractor":"retail",
"moving_company":"retail",
"clothing_store":"retail",
"furniture_store":"retail",
"physiotherapist":"health",
"art_gallery":"retail",
"car_wash":"retail",
"travel_agency":"retail",
"spa":"retail",
"accounting":"finance",
"cafe":"food",
"car_repair":"retail",
"synagogue": "government",
"real_estate_agency":"retail",
"electronics_store":"retail",
"doctor":"health",
"bicycle_store":"retail",
"storage":"retail",
"general_contractor":"retail",
"gym":"health",
"jewelry_store":"retail",
"laundry":"retail",
"insurance_agency":"retail",
"plumber":"retail",
"pet_store":"retail",
"bakery":"food"}